image: node:22.12.0

stages:
  - build
  - deploy

before_script:
  - echo "GitLab CI/CD 시작!"
  - node -v
  - npm -v

# 빌드 단계
build_checkmate_fe:
  stage: build
  only:
    - fe
  script:
    - cd checkmate-fe
    - echo "$FRONTEND_ENV" > .env
    - echo ".env 파일 내용 확인"
    - cat .env
    - npm ci
    - npm run build
  artifacts:
    paths:
      - checkmate-fe/dist

# 로컬 Docker로 자동 배포
deploy_checkmate_fe:
  stage: deploy
  only:
    - fe
  script:
    - echo "🚀 Docker 배포 시작"
    - cd checkmate-fe
    - docker stop checkmate-fe-container || true
    - docker rm checkmate-fe-container || true
    - docker rmi checkmate-fe || true
    - docker build -t checkmate-fe .
    - docker run -d --name checkmate-fe-container -p 3000:80 checkmate-fe
